#
# Production environment overrides
# Merge with: helm upgrade ... -f values.yaml -f values-prod.yaml
#

mailhog:
  enabled: false          # No fake SMTP in prod

sftpgo:
  enabled: false          # External SFTP in prod

sqlServer:
  enabled: false          # External DB in prod

local-path-provisioner:
  enabled: false          # Provisioner pre-installed on prod cluster

observability:
  enabled: false          # Not yet ready for prod

ingress:
  className: traefik
  certName: "CHANGE-ME"
  certIssuer: "CHANGE-ME"

keycloak:
  hostname: "#CHANGEME"
  hostnameStrict: false

daprComponents:
  sftp:
    name: sftpgo-binding
    componentType: bindings.sftp
    rootPath: "."
    address: "#CHANGEME"
    username: "#CHANGEME"
    password: "#CHANGEME"
    insecureIgnoreHostKey: false

keycloakRealmConfiguration:
  adminUser:
    email: "ljacoby@roundtables.us"

  adminEmail: "no-reply@vizoruat.roundtables.us"
  clientPrivateSecret: "ADD-YOUR-SECRET"
  keycloakEnv:
    KC_DB_PASSWORD: "P@55w0rd"
    KEYCLOAK_ADMIN_PASSWORD: "password"
  realmJson:
    clients:
      - clientId: vizor-client
        name: Vizor Client
        rootUrl: "{{ .Values.keycloakRealmConfiguration.serverUrl }}"
        publicClient: true
        directAccessGrantsEnabled: true
        redirectUris:
          - "{{ .Values.keycloakRealmConfiguration.serverUrl }}/*"
        attributes:
          post.logout.redirect.uris: "{{ .Values.keycloakRealmConfiguration.serverUrl }}/*"
        enabled: true
      - clientId: vizor-client-private
        name: Vizor Client Private
        secret: "ADD-YOUR-SECRET"
        publicClient: false
        standardFlowEnabled: true
        directAccessGrantsEnabled: false
        enabled: true
