global:
  namespace: vizor

image:
  registry: 391166432590.dkr.ecr.us-east-1.amazonaws.com
  repo: vizor
  tag: latest
  pullSecrets:
    - ecr-secret

auth:
  clientId: ""

ingress:
  className: traefik
  host: ""
  certName: ""
  certIssuer: ""

resources:
  limits:
    cpu: 256m
    memory: 512Mi
  requests:
    cpu: 64m
    memory: 128Mi

scheduling:
  affinity: {}
  topologySpreadConstraints: []

coreService:
  annotations: {}
  replicas: 2

engagementService:
  annotations: {}
  replicas: 2

interactionService:
  annotations: {}
  replicas: 2
  redisConnectionString: "vizor-redis-master:6379"

useMigrationSql: false

frontend:
  annotations: {}
  replicas: 1

apiProxy:
  replicas: 1

autoscaling:
  enabled: false
  coreService:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  interactionService:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  engagementService:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  frontend:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
  apiProxy:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

daprComponents:
  deploy: true
  state:
    name: statestore
    redisHost: vizor-redis-master:6379
  pubsub:
    name: pubsub
    redisHost: vizor-redis-master:6379

  secrets:
    smtp-host: "#CHANGEME"
    smtp-port: "587"
    smtp-starttls: "true"
    smtp-auth: "true"
    smtp-mail-display-name: "Vizor"
    smtpusername: "#CHANGEME"
    smtppassword: "#CHANGEME"
    SsrsUsername: "#CHANGEME"
    SsrsPassword: "#CHANGEME"
    SsrsBaseUrl: "#CHANGEME"
    SsrsTimeoutSeconds: "300"

  secretStore:
    name: vizor-secretstore
    componentType: secretstores.kubernetes
    secretName: vizor-secrets

  sftp:
    address: "#CHANGEME"
    username: "#CHANGEME"
    password: "#CHANGEME"

sqlServer:
  enabled: true
  image: "mcr.microsoft.com/mssql/server"
  version: "2022-latest"
  releaseName: sqlserver
  username: "sa"
  database: "vizor"
  dbPassword: "#CHANGEME"
  service:
    name: sql-server-service
    port: 1433

persistence:
  enabled: false
  size: 5Gi
  storageClass: local-path

backupCronJob:
  enabled: false
  schedule: "0 2 * * *"
  image: busybox:latest
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

local-path-provisioner:
  enabled: true
  storageClass:
    create: true
    defaultClass: true
    name: local-path
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer
  nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
        - /opt/local-path-provisioner

sftpgo:
  enabled: false

serviceAccount:
  create: true
  name: ""
  annotations: {}

saml:
  jwtkey: "qwertyluopasdfghjklzxcvbnm123456"
  refreshkey: "zxcvbnmlkjhgfdsa0987654321poiuytrewq"
  relaycryptokey: "5AP7b+24XoOKe568t/knpdUVjd8q6rh/+qEiSmBO3HA="
  issuer: "https://vizor.k8s.nbt.local/auth/realms/vizor"
  audience: "vizor"

powerBI:
  baseurl: "https://powerbitest.roundtables.us"

observability:
  enabled: false

mailhog:
  enabled: false

keycloak:
  startMode: "start"
  hostname: ""
  hostnameStrict: false
  httpEnabled: true
  proxyHeaders: "xforwarded"
  managementPort: 9000
