#
# Default values for vizor Helm chart
#

image:
  # -- Image registry, only change if you're using your own images
  registry: harbor.nbt.local
  # -- Image repository
  repo: vizor
  # -- Image tag
  tag: latest
  # -- Any pullsecrets that are required to pull the image
  pullSecrets: []

auth:
  # -- Set this to enable authentication, leave unset to run in demo mode
  clientId:

ingress:
  # -- Ingress host DNS name
  host:
  # -- Set this to enable TLS, leave unset to run in insecure mode
  certName:
  # -- Cert manager issuer, leave unset to run in insecure mode
  certIssuer:

resources:
  limits:
    # -- CPU limit for the containers, leave alone mostly
    cpu: 100m
    # -- Memory limit for the containers, leave alone mostly
    memory: 200M

coreService:
  # -- Dapr store core annotations
  annotations:
  # -- Dapr store core replica count
  replicas: 1

engagementService:
  # -- Dapr store engagement annotations
  annotations:
  # -- Dapr store engagement replica count
  replicas: 1

interactionService:
  # -- Dapr store interaction annotations
  annotations:
  # -- Dapr store interaction replica count
  replicas: 1

# users:
#   # -- Dapr store users annotations
#   annotations:
#   # -- Dapr store users replica count
#   replicas: 1

frontend:
  # -- Dapr store frontend host annotations
  annotations:
  # -- Dapr store frontend host replica count
  replicas: 1

daprComponents:
  # -- Enable to deploy the Dapr components
  deploy: true
  state:
    # -- Dapr state store component name
    name: statestore
    # -- Hostname of redis, fullnameOverride should be used when deploying redis helm chart
    redisHost: vizor-redis-master:6379
  pubsub:
    # -- Dapr pubsub component name
    name: pubsub
    # -- Hostname of redis, fullnameOverride should be used when deploying redis helm chart
    redisHost: vizor-redis-master:6379

  secrets:
      
  
  secretStore:
    name: user-secrets
    componentType: secretstores.kubernetes
    secretName: user-secrets


sqlServer:
  enabled: true
  image: "mcr.microsoft.com/mssql/server"
  version: "2022-latest"
  releaseName: sqlserver
  username: "sa"
  database: "vizor"
  dbPassword: "P@55w0rd"
  service:
    name: sql-server-service
    port: 1433