apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vizor-apps-uat
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: uat
                  repoURL: git@CHANGE-ME:vizor/deploy.git
                  targetRevision: uat
                  namespace: vizor
                  baseValuesFile: values.yaml
                  envValuesFile: values-uat.yaml
                  ingressClassName: traefik
                  ingressHost: vizor-uat.example.com
                  ingressCertName: vizor-uat-tls
                  ingressCertIssuer: letsencrypt-uat
          - list:
              elements:
                - appName: vizor-foundation
                  wave: "-2"
                  layerValuesFile: values-layers/values-foundation.yaml
                - appName: vizor-data-init
                  wave: "-1"
                  layerValuesFile: values-layers/values-data-init.yaml
                - appName: vizor-identity
                  wave: "0"
                  layerValuesFile: values-layers/values-identity.yaml
                - appName: vizor-apps
                  wave: "1"
                  layerValuesFile: values-layers/values-apps.yaml
                - appName: vizor-traffic-autoscale
                  wave: "2"
                  layerValuesFile: values-layers/values-traffic-autoscale.yaml
  template:
    metadata:
      name: '{{appName}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: helm/vizor
        helm:
          valueFiles:
            - '{{baseValuesFile}}'
            - '{{envValuesFile}}'
            - '{{layerValuesFile}}'
          parameters:
            - name: ingress.className
              value: '{{ingressClassName}}'
            - name: ingress.host
              value: '{{ingressHost}}'
            - name: ingress.certName
              value: '{{ingressCertName}}'
            - name: ingress.certIssuer
              value: '{{ingressCertIssuer}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
