apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-proxy
  namespace: vizor
  labels:
    purpose: "vizor-api-gateway"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-proxy
  template:
    metadata:
      labels:
        app: api-proxy
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "api-proxy"
        dapr.io/app-port: "80"
        dapr.io/sidecar-listen-addresses: "0.0.0.0"
    spec:
      containers:
        - name: caddy
          image: caddy:latest
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-inmemory-instance-collector.observability.svc.k8s.nbt:4317
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: caddyfile
          configMap:
            name: caddy-config
