apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: vizor
  labels:
    app: api-proxy
data:
  Caddyfile: |
    :80 {
      # Enable access logs
      log {
        output stdout
        format console
      }
      reverse_proxy localhost:3500

      # # Proxy all Dapr service invocation calls
      # handle_path /v1.0/invoke/{service}/method/* {
      #   reverse_proxy {service}-dapr:3500 {
      #     header_up Host {host}
      #     header_up X-Forwarded-For {remote}
      #   }
      # }

      # Optional health check
      respond /health "OK"
    }
