apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    {{- include "vizor.labels" . | nindent 4 }}
    vizor: frontend
    
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      vizor: frontend
  template:
    metadata:
      labels:
        vizor: frontend
        {{- include "vizor.selectorLabels" . | nindent 8 }}
      annotations:
      {{- with .Values.frontend.annotations }}
          {{- toYaml . | nindent 8 }}
      {{- end }}            
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}    

      containers:
      - name: server
        {{- if .Values.frontend.image }}
        image: {{ .Values.frontend.image }}
        imagePullPolicy: {{ .Values.frontend.imagePullPolicy | default "IfNotPresent" }}
        {{- else }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repo }}/frontend:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
        {{- end }}
        ports:
        - containerPort: 8000

        {{- if .Values.auth.clientId }}
        env:
          - name: AUTH_CLIENT_ID
            value: {{ .Values.auth.clientId }}
        {{- end }}
           
        resources:
        {{- with .Values.resources }}
          {{- toYaml . | nindent 12 }}
        {{- end }}

        readinessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
              - name: "No-Log"
                value: "true"

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    {{- include "vizor.labels" . | nindent 4 }}
    vizor: frontend
spec:
  selector:
    vizor: frontend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
