# Keycloak Realm Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: vizor-realm
  namespace: vizor
data:
  vizor-realm.json: |
{{ .Values.keycloakRealmConfiguration.realmJson | toJson | nindent 4 }}

---
# Keycloak Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: vizor
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: {{ .Values.image.registry }}/{{ .Values.image.repo }}/vizor-themed-keycloak:{{ .Values.image.tag }}
          imagePullPolicy: Always
          args: ["start-dev", "--import-realm"]
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloakRealmConfiguration.keycloakEnv.KEYCLOAK_ADMIN }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloakRealmConfiguration.keycloakEnv.KEYCLOAK_ADMIN_PASSWORD }}
            - name: KC_DB
              value: {{ .Values.keycloakRealmConfiguration.keycloakEnv.KC_DB }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloakRealmConfiguration.keycloakEnv.KC_DB_USERNAME }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.keycloakRealmConfiguration.keycloakEnv.KC_DB_PASSWORD }}
            - name: KC_DB_URL
              value: "jdbc:sqlserver://{{ .Values.sqlServer.service.name }}:{{ .Values.sqlServer.service.port }};databaseName={{ .Values.keycloakRealmConfiguration.keycloakEnv.AUTH_DATABASE_NAME }};encrypt=true;trustServerCertificate=true"
            - name: KC_HTTP_RELATIVE_PATH
              value: {{ .Values.keycloakRealmConfiguration.keycloakEnv.KC_HTTP_RELATIVE_PATH }}
          resources:
            requests:
              memory: {{ .Values.keycloakRealmConfiguration.resources.requested_memory }}
              cpu: {{ .Values.keycloakRealmConfiguration.resources.requested_cpu }}
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
              readOnly: true
      volumes:
        - name: realm-config
          configMap:
            name: vizor-realm
---
# Keycloak Service
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: vizor
  labels:
    app: keycloak
spec:
  ports:
    - port: 8080
  selector:
    app: keycloak
