kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nuage-cluster

containerdConfigPatches:
- |-
  [plugins."io.containerd.cri.v1.images".registry]
    config_path = "/etc/containerd/certs.d"  

nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./certs/nuage-ca.crt
        containerPath: /usr/local/share/ca-certificates/nuage-ca.crt
      - hostPath: ./certs/nuage-ca.crt
        containerPath: /etc/containerd/certs.d/harbor.nbt.local/ca.crt
      - hostPath: kinddata
        containerPath: /mnt/disks/data
      - hostPath: ./registry-configs  # host dir containing registry config files
        containerPath: /etc/containerd/certs.d  # where containerd expects configs
      - hostPath: /var/home/sudipta/Projects/Vizor-Deployment/kind-cluster/theme/TestTheme #Change this to your address
        containerPath: /themes/TestTheme
    # extraPortMappings:
    #   - containerPort: 5000
    #     hostPort: 5000
    #     protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: ./registry-configs  # host dir containing registry config files
        containerPath: /etc/containerd/certs.d  # where containerd expects configs
      - hostPath: /add the address here/theme/TestTheme
        containerPath: /themes/TestTheme
  # - role: worker
  #   extraMounts:
  #     - hostPath: ./registry-configs  # host dir containing registry config files
  #       containerPath: /etc/containerd/certs.d  # where containerd expects configs
  # - role: worker
  #   extraMounts:
  #     - hostPath: ./registry-configs  # host dir containing registry config files
  #       containerPath: /etc/containerd/certs.d  # where containerd expects configs
