{{- if .Values.mailhog.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: docker.io/mailhog/mailhog
          ports:
            - containerPort: 1025 # SMTP
            - containerPort: 8025 # Web UI
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: web
      port: 8025
      targetPort: 8025
  type: NodePort

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mailhog-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  rules:
    - host: mailhog.k8s.nbt.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailhog
                port:
                  number: 8025
{{- end }}
