{{- if .Values.postgresql.enabled }}

# ConfigMap for init SQL
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.releaseName }}-initdb
data:
  init-multiple-dbs.sql: |
{{- range .Values.postgresql.databases }}
    CREATE DATABASE "{{ . }}";
{{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresql.releaseName }}
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgresql.image }}:{{ .Values.postgresql.version }}"
          ports:
            - name: postgres
              containerPort: {{ .Values.postgresql.service.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.dbPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/db
            - name: postgres-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgresql-local-pvc
        - name: postgres-initdb
          configMap:
            name: {{ .Values.postgresql.releaseName }}-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.service.name }}
spec:
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
  type: ClusterIP
  selector:
    app: postgres
{{- end }}
