{{- if and .Values.components.foundation.enabled .Values.persistence.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.sftpPvcName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.persistence.storageClass }} # Will resolve to 'local-path'
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.sftpgoDbPvcName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.persistence.storageClass }} # Will resolve to 'local-path'
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.backupPvcName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.persistence.storageClass }} # Will resolve to 'local-path'
{{ end }}
