{{- if .Values.components.identity.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vizor-keycloak-api-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vizor-keycloak
  template:
    metadata:
      labels:
        app: vizor-keycloak
    spec:
      serviceAccountName: {{ include "vizor.serviceAccountName" . }}
      containers:
        - name: vizor-keycloak
          image: {{ .Values.image.registry }}/{{ .Values.image.repo }}/keycloak-rust-service:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 4567
          env:
            - name: CLIENT_ID
              value: {{ .Values.keycloakRealmConfiguration.clientId }}
            - name: REDIRECT_URI
              value: "{{ .Values.keycloakRealmConfiguration.serverUrl }}/"
          command: ["./app"]

---
apiVersion: v1
kind: Service
metadata:
  name: vizor-keycloak-api-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: vizor-keycloak
  ports:
    - port: 4567
{{- end }}
