{{- if and .Values.components.apps.enabled .Values.sftpgo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vizor.fullname" . }}-sftpgo
  labels:
    app: sftpgo
spec:
  type: {{ .Values.sftpgo.service.type }}
  selector:
    app: sftpgo
  ports:
{{- range .Values.sftpgo.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}

{{- end }}
