# Dev overrides for identity layer
keycloak:
  startMode: "start-dev"

keycloakRealmConfiguration:
  clientPrivateSecret: "ADD-YOUR-SECRET"
  keycloakEnv:
    KC_DB_PASSWORD: "P@55w0rd"
    KEYCLOAK_ADMIN_PASSWORD: "password"
  adminUser:
    email: "ljacoby@roundtables.us"
    password: "Vizor@123"
  userSyncDatabase:
    password: "YourStrongPassw0rd"
  realmJson:
    clients:
      - clientId: vizor-client-private
        name: Vizor Client Private
        secret: "ADD-YOUR-SECRET"
        publicClient: false
        standardFlowEnabled: true
        directAccessGrantsEnabled: false
        enabled: true
