argocdNamespace: argocd
project: default

applicationSet:
  name: vizor-apps-prod

env:
  name: prod
  repoURL: "#CHANGEME"
  targetRevision: main
  destinationNamespace: vizor
  baseValuesFile: values.yaml
  envValuesFile: values-prod.yaml
  # redisServiceName: optional; default vizor-redis-master. Dapr redisHost derived from Redis app.
  ingress:
    className: traefik
    host: "#CHANGEME"
    certName: "#CHANGEME"
    certIssuer: "#CHANGEME"
