# Example overrides for argocd/root/prod
argocdNamespace: argocd
project: default

sftpgo:
  enabled: false

applicationSet:
  name: vizor-apps-prod

env:
  name: prod
  repoURL: git@git.prod.example.com:vizor/deploy.git
  targetRevision: main
  destinationNamespace: vizor
  baseValuesFile: values.yaml
  image:
    projectRegistry: registry.vizor-registry.svc.k8s.vizor.local:5000
  ingress:
    className: traefik
    host: vizor.example.com
