apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqlserver-db
spec:
  type: configuration.redis
  version: v1
  metadata:
  - name: connectionString
    value: "Server={{ .Values.daprComponents.secrets.sqlServer }},1433;Database={{ .Values.sqlServer.database }};User Id={{ .Values.sqlServer.username }};Password={{ .Values.daprComponents.secrets.dbPassword }};"
