
{{- if .Values.daprComponents.deploy }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.daprComponents.secretStore.name }}
spec:
  type: {{ .Values.daprComponents.secretStore.componentType }}
  version: v1
  metadata:
  - name: "secretStore"
    value: "kubernetes"
scopes:
  - "*"
{{ end }}
