apiVersion: v1
kind: Service
metadata:
  name: interaction-service
  namespace: vizor
spec:
  selector:
    vizor: interaction-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
