apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-migrations
  labels:
    {{- include "vizor.labels" . | nindent 4 }}
    vizor: migrations
  annotations:
    "helm.sh/hook": pre-upgrade,post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  ttlSecondsAfterFinished: 30 # keeps the Job visible only for 60 seconds
  backoffLimit: 4
  template:
    metadata:
      labels:
        vizor: migrations
        {{- include "vizor.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: {{ .Values.image.registry }}/{{ .Values.image.repo }}/ef-core-migration:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                secretKeyRef:
                  name: vizor-secrets
                  key: connectionString
          workingDir: /app
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              RETRIES=5
              DELAY=10
              echo "This image contains following migrations:"
              cat /app/migrations.txt
              for i in $(seq 1 $RETRIES); do
                echo "Attempt $i: Running migration..."
                /opt/mssql-tools/bin/sqlcmd -S "$MSSQL_CONNECTIONSTRING" -i /app/migration.sql \
                  && echo "List of migrations applied to the server" \
                  && /opt/mssql-tools/bin/sqlcmd -S "$MSSQL_CONNECTIONSTRING" -Q -Q "SELECT MigrationId, ProductVersion FROM __EFMigrationsHistory" \
                  && break
                echo "Migration failed. Retrying in $DELAY seconds..."
                sleep $DELAY
              done
              echo "Migration completed or max retries reached."
