{{- if and .Values.components.foundation.enabled .Values.daprComponents.deploy }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.daprComponents.pubsub.name }}
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: "vizor-redis-master-master.{{ .Release.Namespace }}.svc.cluster.local:6379"
  - name: redisPassword
    value: ""
{{ end }}
