{{- if .Values.daprComponents.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.daprComponents.secretStore.secretName }}
type: Opaque
data:
  {{- range $key, $val := .Values.daprComponents.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- $connectionString := printf "Server=%s,%.0f;Database=%s;User Id=%s;Password=%s;" .Values.sqlServer.service.name .Values.sqlServer.service.port .Values.sqlServer.database .Values.sqlServer.username .Values.sqlServer.dbPassword }}
  connectionString: {{ $connectionString | b64enc }}
{{- end }}
