{{- if .Values.daprComponents.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.daprComponents.secretStore.secretName }}
type: Opaque
data:
  {{- range $key, $val := .Values.daprComponents.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{ end }}
