{{- if and .Values.components.foundation.enabled .Values.daprComponents.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
{{- end}}

---

{{- if and .Values.components.foundation.enabled .Values.daprComponents.deploy }}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vizor-secret-reader
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "vizor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

{{- end}}
