apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sftpgo-binding
spec:
  type: bindings.sftp
  version: v1
  metadata:
    - name: rootPath
      value: "/srv/sftpgo/data/vizor" # The home directory for the 'vizor' user
    - name: address
      value: "vizor-sftpgo:2022" # Your SFTPGo service address
    - name: username
      value: "vizor" # SFTPGo user
    - name: password
      secretKeyRef:
        name: vizor-secrets # The name of the Kubernetes Secret
        key: sftpgoPassword 
    - name: insecureIgnoreHostKey
      value: "true" # Caution: Use only for testing. Set to "false" in production.