apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: "{{ .Values.daprComponents.sftp.name }}"
spec:
  type: bindings.sftp
  version: v1
  metadata:
    - name: rootPath
      value: "{{ .Values.daprComponents.sftp.rootPath }}" # The home directory for the 'vizor' user
    - name: address
      value: "{{ .Values.daprComponents.sftp.address }}" # Your SFTPGo service address
    - name: username
      value: "{{ .Values.daprComponents.sftp.username }}" # SFTPGo user
    - name: password
      secretKeyRef:
        name: vizor-secrets # The name of the Kubernetes Secret
        key: sftpPassword
    {{ - if .Values.daprComponents.sftp.insecureIgnoreHostKey }}
    - name: insecureIgnoreHostKey
      value: "true" # Caution: Use only for testing. Set to "false" in production.
    {{ - end }}
