{{- if and .Values.components.platformSupport.enabled .Values.sftpgo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vizor-sftpgo-description
  namespace: {{ .Release.Namespace }}
data:
  description.json: |
    {{- .Values.sftpgo.description | nindent 4 }}

{{- end }}
