{{- if .Values.sftpgo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vizor.fullname" . }}-sftpgo-description
data:
  description.json: |
    {
      "admins": [
        {
          "id": 1,
          "username": "admin",
          "password": "admin",
          "status": 1,
          "permissions": ["*"]
        }
      ],
      "users": [
        {
          "id": 2,
          "username": "vizor",
          "password": "password",
          "status": 1,
          "home_dir": "/srv/sftpgo/data/vizor",
          "permissions": ["read", "write"]
        }
      ],
      "folders": [],
      "version": 7
    }
{{- end }}
