apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vizor-data-init
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vizor
  source:
    repoURL: git@git.nbt.local:vizor/deploy.git
    targetRevision: HEAD
    path: helm/vizor
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
        - values-layers/values-data-init.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
