apiVersion: v1
kind: ConfigMap
metadata:
  name: sftpgo-dapruser-config
  namespace: {{ .Values.global.namespace }}
data:
  payload.json: |
    {
      "username": "dapruser",
      "home_dir": "/srv/dapruser",
      "public_keys": [
        "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3Uuus8DG2gxyI5RfN4cccPD+WHvtOoP9RAockpJ/iibUukJQhVc+eoaZZNpd9IaCaKP08ttk3awdMYCExCv0qfqKkCSph8qDazLMSZroqiAsX1V5z8ofhAo3OxBxrXSpIBGYpc5uGfzgaGd0CuD2ekK6zVPOOb6F5eZGgKCi+RpGlYkfUrnh1pPTyf0EdCKMF0mxoUV0AhySUb8S+aPjugx/Sk17lMU1xw4WpIsWPhtOpy1YnWZf3MEJ1q/3/IU8gwqM0YJeygfRFDE5675CWfSTpv6XjGn5/LAhhdXZrfyJTvE0mhLlcl/8JMmMk7wn+5YxULAfVame6UGq5KaoBK3oGfQXd5E6CnbLzleiO7wn384SIZQz4mmt97hL/L6o9Do6tuTAYlAiyElJw+/h+tDQY4BHbxTE5GOAKUVZsj/B4Vy7+p+2vgInCPcjbdRFpYXKJB2ZZz0w0nzUxViVVRuW768G7HErn5pgGEa7OyqX6W+0eN+ayB6QoRvMUWk2Cl1vmO+k20q4DIJd2LWqyKeJP43t1cik4x0ZKbuGvytIZhRxZZbno2k2+XAhLDbN8V86qEt71CqvUaPPQcny6QgPAcBHbDLdWjdNq4v+Oji4ESRLA2aKPuUzv0iCvFbGA7EErMorgTTnpR1lToWtjU4BpGxYM/wIEQLuocSbeYw== veersingh@NBT-Veer-Mini.local"
      ],
      "permissions": {
        "/": ["*"]
      },
      "uid": 1001,
      "gid": 1001,
      "status": 1,
      "description": "User managed by Kubernetes job"
    }
