apiVersion: v1
kind: Secret
metadata:
  name: dapr-sftp-private-key
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  sshKey: {{ .Values.daprComponents.secrets.sftpPrivateKey | b64enc }}