apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.daprComponents.sftpBinding.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: bindings.sftp
  version: v1
  metadata:
  - name: host
    value: {{ .Release.Name }}-sftpgo.{{ .Values.global.namespace }}.svc.cluster.local
  - name: port
    value: "{{ .Values.sftpGo.port }}"
  - name: username
    value: {{ .Values.daprComponents.sftpBinding.username }}
  - name: privateKey
    secretKeyRef:
      name: dapr-sftp-private-key
      key: sshKey
  - name: rootPath
    value: {{ .Values.daprComponents.sftpBinding.rootPath }}
  - name: insecureIgnoreHostKey
    value: "{{ .Values.daprComponents.sftpBinding.insecureIgnoreHostKey }}"
  - name: operationTimeout
    value: "30"
  - name: pollInterval
    value: "10"
  - name: metadataMode
    value: "0777"
  - name: deleteBeforeCreate
    value: "false"
  auth:
    secretStore: {{ .Values.daprComponents.secretStore.name }}