{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vizor-sftpgo
  namespace: {{ .Release.Namespace }}
  labels:
    app: sftpgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftpgo
  template:
    metadata:
      labels:
        app: sftpgo
    spec:
      serviceAccountName: {{ include "vizor-sftpgo.serviceAccountName" . }}
      {{- with .Values.scheduling.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sftpgo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 2022
            - containerPort: 8080
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: sftpgo-data
              mountPath: /srv/sftpgo
            - name: sftpgo-config
              mountPath: /etc/sftpgo/config.yml
              subPath: config.yml
            - name: sftpgo-description
              mountPath: /etc/sftpgo/description.json
              subPath: description.json
      volumes:
        - name: sftpgo-data
          persistentVolumeClaim:
            claimName: vizor-sftpgo-data
        - name: sftpgo-config
          configMap:
            name: vizor-sftpgo-config
        - name: sftpgo-description
          configMap:
            name: vizor-sftpgo-description
{{- end }}
