{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vizor-sftpgo
  namespace: {{ .Release.Namespace }}
  labels:
    app: sftpgo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sftpgo
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
{{- end }}
