{{- if .Values.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.daprComponent.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: bindings.sftp
  version: v1
  metadata:
    - name: rootPath
      value: "{{ .Values.daprComponent.rootPath }}"
    - name: address
      value: "{{ .Values.daprComponent.address }}"
    - name: username
      value: "{{ .Values.daprComponent.username }}"
    - name: password
      secretKeyRef:
        name: {{ .Values.global.secretName }}
        key: sftpPassword
    - name: startupDelaySeconds
      value: "30"
    - name: timeout
      value: "60s"
    - name: maxConnections
      value: "10"
    - name: keepAliveInterval
      value: "30s"
    {{- if .Values.daprComponent.insecureIgnoreHostKey }}
    - name: insecureIgnoreHostKey
      value: "true"
    {{- end }}
{{- end }}
