argocdNamespace: argocd
project: default

applicationSet:
  name: vizor-apps-dev

env:
  name: dev
  repoURL: git@git.nbt.local:vizor/deploy.git
  targetRevision: develop
  destinationNamespace: vizor
  baseValuesFile: values.yaml
  envValuesFile: values-dev.yaml
  ingress:
    className: traefik
    host: ""
    certName: ""
    certIssuer: ""
